name: UtilCI

on:
  push:
    branches: [ master ]

jobs:
  phpunit:
    strategy:
      matrix:
        php_version: [8.2]
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: redis,xdebug
          coverage: xdebug
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Git Version
        run: git --version
      - name: Force Synchronization Code
        run: bash ./ci/branch.sh --branch=master
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress
      - name: PHP CS Fixer
        run: bash ./ci/cs-fix.sh
      - name: PHPUnit Check
        run: composer phpunit
